### ISSUE TITLE
Spartan Chess

### ISSUE THREAD

**Issue by CPagador** [fairy-stockfish/Fairy-Stockfish#260]
Hi,

I'd like Spartan Chess was implemented in Fairy Stockfish.

https://www.chessvariants.com/rules/spartan-chess

Some engines play this variant:

Sangga
Nebiyu
Sjaak
Oberon
Leonidas
FairyMax
Catalyst
SjaakII

It is a very nice variant and it looks even from both sides.

Regards,
Carlos

**Comment by PraseodymiumSpike** [comment]
"Duple-Check & Mate
"If both Spartan Kings are placed under simultaneous attack this is a form of check called duple-check. It is illegal for the Spartan to make a move that will place both of his Kings underattack. With both Kings under attack, the Spartan loses if on his move he is unable to remove at least one King from attack. In such case the game ends in checkmate."
-[Spartan Chess](-https://www.chessvariants.com/rules/spartan-chess)
I propose this be expanded to nTupleCheck. Basically, this would work as follows:
It is illegal to make any move such that n of your kings are in check at the same time on the opponent's turn. It is okay to have n-1 in check or to make a move that results in such (Of course, extinctionPseudoRoyal might prevent this, as in an implementation of Spartan Chess given that there is only 1 Black King remaining, but the nTupleCheck won't.). If n of your kings are in check at the same time on your turn, and there is no way to reduce that number to n-1 or fewer by the time of your opponent's turn, you lose.

**Comment by PraseodymiumSpike** [comment]
Note that n doesn't **have** to be the maximum number of kings on a side, though that would probably be the most common use case for this. Also, it would be cool to have a rule that allows n to change dynamically as the number of kings increases or decreases.
