### ISSUE TITLE
Cannon shogi

### ISSUE THREAD

**Issue by ianfab** [fairy-stockfish/Fairy-Stockfish#304]
https://en.wikipedia.org/wiki/Cannon_shogi
https://www.chessvariants.com/shogivariants.dir/cannonshogi.html

Should already be possible to configure in variants.ini without code changes, just requires to write down the configuration from the rules.

**Comment by PraseodymiumSpike** [comment]
I believe the flying cannons are not currently supported. Is this correct?

**Comment by PraseodymiumSpike** [comment]
If correct, I suggest the "good first issue" tag be removed.

**Comment by ianfab** [comment]
I only remember to have briefly checked the Betza notations in the [wikipedia article when it still existed](https://web.archive.org/web/20210302195405/https://en.wikipedia.org/wiki/Cannon_shogi#Movement_diagrams) and they looked compatible to me. If these are wrong it might not be compatible.

**Comment by PraseodymiumSpike** [comment]
I believe you may have missed that the Promoted cannons can jump over an **unlimited** number of Pieces. Is this supported?
