### ISSUE TITLE
Chigorin Chess Pawn Promotion

### ISSUE THREAD

**Issue by alwey** [fairy-stockfish/Fairy-Stockfish#4]
I noticed that Fairy-Stockfish ocasionally wants to promote white Pawns to Queens and black Pawns to Chancellors. R. Betza recommends limiting the promotions to the sides' piece types available at start. 

https://en.wikipedia.org/wiki/Chigorin_Chess
http://www.chessvariants.com/diffsetup.dir/chigorin.html

**Comment by ianfab** [comment]
Thanks for the report. For simplicity, so far I only added symmetrical pawn promotion options, so the behavior is expected although not correct. Asymmetrical promotions are still to be added.
