### ISSUE TITLE
Berolina chess

### ISSUE THREAD

**Issue by ianfab** [fairy-stockfish/Fairy-Stockfish#51]
Support [Berolina chess](https://en.wikipedia.org/wiki/Berolina_chess) or more generally variants with berolina pawns.

**Comment by Belzedar94** [comment]
Please refer to the below link to see how GUI's (Cutechess in this case) extend the FEN to allow Berolina Pawns and the consequent en-passant move.

[https://github.com/cutechess/cutechess/pull/194](url)
