### ISSUE TITLE
Castling does not work.

### ISSUE THREAD

**Issue by FlXME** [fairy-stockfish/Fairy-Stockfish#632]
### Problem
I have the position `rnbqk2r/pppppp1p/5n1b/6p1/3Q4/2P3P1/PP1PPP1P/III1KIII b kq - 4 4` and want to castle by doing `e8h8` but the board does not change when I run `position fen rnbqk2r/pppppp1p/5n1b/6p1/3Q4/2P3P1/PP1PPP1P/III1KIII b kq - 4 4 moves e8h8` via UCI and `e8h8` does not seem to be recognized as a valid move by the engine.
All other moves leading up to this seem to be working perfectly fine though.

```
+---+---+---+---+---+---+---+---+
| r | n | b | q | k |   |   | r |8 *
+---+---+---+---+---+---+---+---+
| p | p | p | p | p | p |   | p |7
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | n |   | b |6
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   | p |   |5
+---+---+---+---+---+---+---+---+
|   |   |   | Q |   |   |   |   |4
+---+---+---+---+---+---+---+---+
|   |   | P |   |   |   | P |   |3
+---+---+---+---+---+---+---+---+
| P | P |   | P | P | P |   | P |2
+---+---+---+---+---+---+---+---+
| I | I | I |   | K | I | I | I |1
+---+---+---+---+---+---+---+---+
  a   b   c   d   e   f   g   h
```

### variants.ini
```
[king-white:chess]
immobile = i
startFen = rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/IIIQKIII w kq - 0 1
pieceToCharTable = PNBRQ.............I..Kpnbrq.............i..k
```

**Comment by ianfab** [comment]
In this case the problem is that the castling notation only is "king captures rook" in 960 variants, but not in normal chess/variants, see e.g. https://fairy-stockfish.github.io/chess-variant-standards/#uci. So to fix it you need to replace `e8h8` by `e8g8`. You can also e.g. use `go perft 1` to get the list of legal moves.
