### ISSUE TITLE
Custom DoubleStep pieces

### ISSUE THREAD

**Issue by FlXME** [fairy-stockfish/Fairy-Stockfish#634]
### Problem
I made a custom pawn, but I encountered a problem: the doubleStep check is hardcoded with the regular pawn in both ucioption.cpp and apiutil.h. As a result, the custom pawn is unable to execute a double step (e.g. e2e4) because the move is rejected.

### Change request
Please enable custom pawn types to perform double steps or add a PieceSet that is allowed to double step and includes the regular pawn by default.

### variants.ini
```
[demo]
customPiece1 = m:fmWfceF
pawnTypes = m
startFen = rnbqkbnr/pppppppp/8/8/8/8/MMMMMMMM/RNBQKBNR w KQkq - 0 1
```

**Comment by ianfab** [comment]
This is already possible, see e.g. https://github.com/fairy-stockfish/Fairy-Stockfish/blob/bf310e8cbcd8fd171ef0a1b8a5144ea3681b0017/src/variants.ini#L296

Just make sure that you include "initial moves" (`i`) in the Betza notation as with the double step in the above example..
