### ISSUE TITLE
Possible to Capture Own Pieces?

### ISSUE THREAD

**Issue by Yowwowwow** [fairy-stockfish/Fairy-Stockfish#641]
I made a chess/shogi like game but was unable to deeply analyze it on my own, so I am trying to use fairy stockfish.
However, one of the main mechanics of the game is that you can capture your own pieces (including king, although you instantly lose in that case), and all pieces captured by you go to your hand, regardless of who owned them. You can drop pieces in your hand onto an empty square just like shogi. Is it possible to implement this in fairy stockfish?

**Comment by ianfab** [comment]
This is currently not supported, but already filed as #608.
