### ISSUE TITLE
Allow promotion to opponent's pieces

### ISSUE THREAD

**Issue by gnunicode** [fairy-stockfish/Fairy-Stockfish#646]
Allowing white pieces to promote to black pieces and vice versa would enable support of Andernach chess (pieces change colour after each capture) and super-Andernach chess (pieces change colour after each move).
https://en.wikipedia.org/wiki/Andernach_chess

EDIT: I realised it's not quite so simple as this runs into issues with normal pawn promotions. Still a general solution would be nice since neither of those variants are commonly played, and there are other variants featuring promotion to the opponent's pieces.

**Comment by Belzedar94** [comment]
I'm also interested in Andernach! So I would leave it open for the far future unless Fabian thinks this is a hard limit in terms of design
