### ISSUE TITLE
Bug - flag to win is not available, at least in king of the Hill and Shinobi

### ISSUE THREAD

**Issue by yixin-zhu** [fairy-stockfish/Fairy-Stockfish#653]
It seems fairy-stockfish doesn't know move flag piece into the flag area is a win. I only test king of the Hill and Shinobi, but it can not find  out the win move in very simple position. Also, user moving it manually into flag area was not recognized as a win.

**Comment by ianfab** [comment]
I can not reproduce this. Can you please specify the exact steps to reproduce this?

**Comment by yixin-zhu** [comment]
Yes, this problem could be reproduced by following command.

I use Fairy-Stockfish executable file for Windows.

Get to a directory where fairy-stockfish-largeboard_x86-64.exe and variant.ini exist.
```bash
fairy-stockfish-largeboard_x86-64.exe load variant.ini
xboard
variant shinobi
setboard 8/K7/8/8/8/8/7k/8[] w - - 0 1
sd 20
go
```
Then, you can see the problem.

In this position, where white king at a7 and black king at h2, white king should move to a8 and b8 and win immediately because *8 and *1 are flag regions.

However, fairy-stockfish plays a7b6. Then I play the black king to h1.

```bash
h2h1
```
But it is not a black win 0-1.

I doubt the variant.ini file is wrong. So I check it and find flagRegionWhite = *8 and flagRegionBlack = *1. It seems to be correct.

```text
# Shinobi Chess
# https://vchess.club/#/variants/Shinobi
[shinobi:chess]
variantTemplate = shogi
pieceToCharTable = PNBRQ.DJMLH.....CKpnbrq.djmlh.....ck
pocketSize = 8
commoner = c
bers = d
archbishop = j
fers = m
shogiKnight = h
lance = l
promotionRegionWhite = *7 *8
promotionRegionBlack = *2 *1
promotionPieceTypes = -
promotedPieceType = p:c m:b h:n l:r
mandatoryPiecePromotion = true
stalemateValue = loss
perpetualCheckIllegal = true
startFen = rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/LH1CK1HL[LHMMDJ] w kq - 0 1
pieceDrops = true
whiteDropRegion = *1 *2 *3 *4
blackDropRegion = *5 *6 *7 *8
immobilityIllegal = true
flagPiece = k
flagRegionWhite = *8
flagRegionBlack = *1
```

I doubt the game is not recognized as shinobi game but a classical chess game. So I add some pieces of shinobi to the board.

```bash
fairy-stockfish-largeboard_x86-64.exe load variant.ini
xboard
variant shinobi
setboard 8/K7/LH6/8/8/8/6+pk/8[] w - - 0 1
sd 20
go
```
But the result is same, fairy-stockfish plays b6c8+. It misses the win move a7a8 or a7b8.

**Comment by ianfab** [comment]
For me this is working fine. Could it be that you are using an older executable, e.g., from the last official release? You should pick the INI and the executable from the same version to make sure they are compatible.
