### ISSUE TITLE
Can it be deployed on a distributed system?

### ISSUE THREAD

**Issue by wawahuy** [fairy-stockfish/Fairy-Stockfish#660]
Is there a way to deploy it on two or multiple different computers to collectively process a chess game?
I want to use a LAN network to communicate between the machines.

**Comment by ianfab** [comment]
Distributed analysis is supported e.g. by https://github.com/lichess-org/fishnet or https://github.com/gbtami/fairyfishnet.

If you instead mean to analyze a single position with multiple machines, that would require merging the [cluster branch from official Stockfish](https://github.com/official-stockfish/Stockfish/tree/cluster) to support MPI. However, this to my knowledge this does not scale that well and also needs very high bandwidth.
