### ISSUE TITLE
Cannot find any Advisor in the source code

### ISSUE THREAD

**Issue by gms2009** [fairy-stockfish/Fairy-Stockfish#661]
This flavor of stockfish can play chinese chess(xiangqi) very well,  but I cannot find any info of Advisor(the piece right beside king) in the source code,  Is it using another word or simply not necessary or something else?

**Comment by RainRat** [comment]
This?

https://github.com/fairy-stockfish/Fairy-Stockfish/blob/ff790b70f3f3df87352d031cd59ebf9e714aa0ba/src/variant.cpp#L1660

**Comment by ianfab** [comment]
A piece that can move one square diagonally in chess variants is commonly referred to as a fers, which is also the name used in Fairy-SF.

**Comment by gms2009** [comment]
Got it, thanks
