### ISSUE TITLE
Optimize Connect in directions.

### ISSUE THREAD

**Issue by RainRat** [fairy-stockfish/Fairy-Stockfish#665]
connect_directions is computed from connect_horizontal, connect_vertical, and connect_diagonal every loop. Would be more efficient to compute once at initialization.

**Comment by RainRat** [comment]
Ok, I'm not sure if I'm doing it correct, but here's my attempt:

https://github.com/RainRat/Fairy-Stockfish/commits/optimizeConnect

**Comment by ianfab** [comment]
You should reset the connect directions before initializing them to make sure that re-running the method won't cause problems, e.g., in case of variant inheritance. Other than that looks fine.
