### ISSUE TITLE
Add Faceoff Chess to FSF

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [fairy-stockfish/Fairy-Stockfish#669]
I’ve created chess variant with rule which was borrowed from XiangQi and upgraded (and also brought to Dan Lee’s Synochess and Empire).

Kings cannot face each other not only horizontally or vertically, but also **diagonally**. Stalemate, though, is draw, but not the King vs. King + 2 Knights endgame.
Can you add it please?

**Comment by ianfab** [comment]
For diagonal faceoff please use #188
