### ISSUE TITLE
Nighty Zones (Amazons with Knights instead)

### ISSUE THREAD

**Issue by Rechefiltr-is-Fire** [fairy-stockfish/Fairy-Stockfish#670]
I’ve created a Amazons-based game where all Queen-line activity (moving and shooting) becomes Knight-leap (Archers become Lancers).

I’ve even drawn all pieces images (except for checkers-like pictures).

**Comment by ianfab** [comment]
You mean like this? https://github.com/fairy-stockfish/Fairy-Stockfish/blob/8549ed1dd01e641e234e073a0b86dac70923dcf4/src/variants.ini#L1542-L1548

**Comment by Rechefiltr-is-Fire** [comment]
I mean Amazons on PlayStrategy (10x10)
and variant is strongly based on it.

**Comment by gbtami** [comment]
https://github.com/fairy-stockfish/Fairy-Stockfish/blob/master/src/variant.cpp#L1636

**Comment by Rechefiltr-is-Fire** [comment]
`    }
#ifdef ALLVARS
    // Game of the Nighty Zones
    Variant* nightyzones_variant() {
        Variant* v = chess_variant_base()->init();
        v->pieceToCharTable = "....N.....................n.................";
        v->maxRank = RANK_10;
        v->maxFile = FILE_J;
        v->reset_pieces();
        v->add_piece(CUSTOM_PIECE_1, 'n', "mN");
        v->startFen = "3n2n3/10/10/n8n/10/10/N8N/10/10/3N2N3 w - - 0 1";
        v->stalemateValue = -VALUE_MATE;
        v->arrowGating = true;
        return v;
    }
#endif`

**Comment by ianfab** [comment]
What you are suggesting literally is just the variant I linked above simply with a different board size (and setup). If you need help configuring a variant feel free to ask on discord, but in terms of a feature request I consider this as closed.

**Comment by Rechefiltr-is-Fire** [comment]
How to embed that in PlayStrategy, though?
