### ISSUE TITLE
王异常移位

### ISSUE THREAD

**Issue by jialaolian11** [fairy-stockfish/Fairy-Stockfish#673]
rnbkq1n1/p3b3/2p2rp1/1p3p1p/3Pp2N/PBQ1P1P1/1PP1N2P/R1BK1R2 w Kk - 0 15 ,预测结果:bestmove d1g1

**Comment by zhuomuniao-MU** [comment]
fake news!

**Comment by zhuomuniao-MU** [comment]
fake  news!

**Comment by jialaolian11** [comment]
In version 14, difficulty -20, using this data, Wang moves out of position

**Comment by jialaolian11** [comment]
At 14 version, the difficulty - 20 cases, using the data "rnbkq1n1 / p3b3/2 p3p1p p2rp1/1/3 pp2n pp1n2p/R1BK1R2 w/PBQ1P1P1/1 Kk - 0 15", engine return bestmove d1g1

**Comment by ianfab** [comment]
You defined chess960 castling rights with `Kk`, so Fairy-SF is allowed to castle. Not a bug.

**Comment by jialaolian11** [comment]
Hello, what is the translocation right of chess 960?  I see on https://lichess.org/zh, when the king moves, there can't be chess pieces in the way of his moving route

**Comment by jialaolian11** [comment]
请问可以在哪里设置配置，可以让我使用https://lichess.org/zh上的标准模式

**Comment by jialaolian11** [comment]
Where can I set up the configuration so I can use the standard mode on https://lichess.org/zh

**Comment by zhuomuniao-MU** [comment]
> You defined chess960 castling rights with `Kk`, so Fairy-SF is allowed to castle. Not a bug.

1

**Comment by ianfab** [comment]
Fairy-SF by default uses the UCI protocol, and the UCI protocol puts the responsibility of validating the input on the GUI that communicates with the engine. So lichess validates the position and only accepts correct castling rights. If your GUI doesn't do that, then it is a bug of the GUI.
