### ISSUE TITLE
Segfaults when variants.ini's castling in FEN is incorrect

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [fairy-stockfish/Fairy-Stockfish#678]
`fairy-stockfish check variants.ini` says it's ok - it ends up crashing when loaded
Fairy Chess playground functions properly
```
[oopsallknights:chess]
archbishop = h
bishop = -
amazon = a
queen = -
chancellor = e
rook = -
king = k:KN
promotionPieceTypes=aehn
castling = false
startFen = ENHAKHNE/PPPPPPPP/8/8/8/8/pppppppp/enhakhne w KQkq - 0 1
pieceToCharTable = PN..........H..E..AKpn..........h..e..ak
```

**Comment by ianfab** [comment]
Thanks for reporting. I transferred this to the Fairy-Stockfish repository, since rule related issues almost always are down to the core rule implementation, which is in Fairy-SF itself also for dependent projects.
