### ISSUE TITLE
Incorrect Evaluation of Stalemate

### ISSUE THREAD

**Issue by PraseodymiumSpike** [fairy-stockfish/Fairy-Stockfish#686]
https://discord.com/channels/779317816897699850/791247944463417374/1131175562291990533

also applies to royal ferz, etc.

I suggest that draw by dead position be removed, even for chess. It is too difficult to calculate and took significant research to calculate for normal chess. This is near-impossible to do automatically for arbitrary supported variants. The only exception is when all the pieces are colorbound, and stalemate is a draw. Then, it's easy to tell sometimes. I propose this change be made immediately as incorrectly determining the value of a game is a serious bug.

**Comment by ianfab** [comment]
Thanks for reporting. Just for clarification, the insufficient material calculation we are referring to here is exclusively used by the libraries, i.e., in effect the GUIs, like fairyground and pychess, but not by the engine.

It is generally implemented very conservatively to avoid false positives, it does not really do a dead position detection. Therefore we should just fix this buggy scenario.
