### ISSUE TITLE
dropRegion[Color][Piece]

### ISSUE THREAD

**Issue by PraseodymiumSpike** [fairy-stockfish/Fairy-Stockfish#688]
I think it would be nice to have something of the form dropRegion[Color][Piece] that could be used to configure where a piece can be dropped. It would completely override mobilityRegion[Color][Piece] for that piece, but if it wasn't there, the drop region would fall back to the mobility region. If a piece is dropped outside of its mobility region, it should be able to move into its mobility region assuming that that's its move. so if a wazir with a mobility region that's just the a file is dropped on b1, it should be able to move to a1, but then, it couldn't move back to b1 unless it was captured and re-dropped. Obviously, it wouldn't be able to move from b1 to a2 or something. And it also couldn't move from b1 to b2 or c1. It couldn't even move from b2 to b1 unless it was captured and dropped on b1.

**Comment by ianfab** [comment]
This is already filed as https://github.com/fairy-stockfish/Fairy-Stockfish/issues/618
