### ISSUE TITLE
Simultaneous Kings

### ISSUE THREAD

**Issue by PraseodymiumSpike** [fairy-stockfish/Fairy-Stockfish#725]
So I have recently come across [this army](https://docs.google.com/document/d/1uT7BKK3BaNhuIhP3r_MIjx7ks8cIKDlRX36VFISRFxc/edit?usp=sharing). Note that they use the word "Titan" to essentially mean what we would call a pseudo-royal piece. This is a weird thing to like, but this army can be checkmated in beautiful ways, as shown by [this game](https://gerumai-6076.rostiapp.cz/custom/#c3BlY3RhdGUvNzkwNDAzNzM3OTU2Mw==) in which it opposes a version of the East from `schism`. I think that the 2-king mechanic should be supported.

**Comment by ianfab** [comment]
This would first require something like multimoves #343 or the like.

**Comment by PraseodymiumSpike** [comment]
> This would first require something like multimoves #343 or the like.

I think you could represent it as a duck-like thing.
