### ISSUE TITLE
Need help about HashingKey of XiangQi's opening book (.obk)

### ISSUE THREAD

**Issue by biennguyen13** [fairy-stockfish/Fairy-Stockfish#726]
Hi.

I'm researching about "hash key" in opening book  ( .obk - sqlite3 format ) which created by hashing algorithm in Xiangqi.
I found this specification file [HASHKEY](https://github.com/ianfab/Fairy-Stockfish/files/4674814/HASHKEY.txt)

I understand the meaning of "chess",  it is a type of chess pieces, from 0 to 13.

> // 棋子名称 ：        空  将  车  炮  马  象  士  兵
> //int RedPiece[8] = { -1, 32, 33, 35, 37, 39, 41, 43 }; 红方
> //int BlkPiece[8] = { -1, 16, 17, 19, 21, 23, 25, 27 }; 黑方
> 
> const int FPiece14[48]=
> {
>         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
>         0,1,1,2,2,3,3,4,4,5,5,6,6,6,6,6,
>         7,8,8,9,9,10,10,11,11,12,12,13,13,13,13,13
> }

If the piece is a Red Rook then it is 33 => FPiece14[33] => the result is 8.

> const unsigned __int64 ZobristTable[14][256] =
> {...}
> 
> 计算HASHKEY
> ZobristLock ^= ZobristTable[chess][square];

Now, I understand that I can get the value of piece in ZobristTable at [8][square]

But I'm stuck at the "square", I don't understand how to get it.

As far as I know, this algorithm uses a board with 256 squares (16 x 16). In XiangQi, its board has 90 squares below:

> 90个棋子的square（上黑下红）
> static const unsigned char C90[90] =   
> {
>         0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b,
>         0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b,
>         0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b,
>         0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b,
>         0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x7b,
>         0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b,
>         0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b,
>         0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab,
>         0xb3, 0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb,
>         0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xcb
> };

In my case, the Red Rook stands on square 195 (0xc3). So the result I can get is ZobristTable at [8][195]. Am I doing it right?
I try to hash the table in the first state, it like the FEN  "rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w"

My test code:

> uint64_t ZobristPlayer = 0xA0CE2AF90C452F58;
> uint64_t finalKey = 0;
> 
> // Black
> finalKey ^= ZobristTable[1][51];
> finalKey ^= ZobristTable[3][52];
> finalKey ^= ZobristTable[4][53];
> finalKey ^= ZobristTable[5][54];
> finalKey ^= ZobristTable[0][55];
> finalKey ^= ZobristTable[5][56];
> finalKey ^= ZobristTable[4][57];
> finalKey ^= ZobristTable[3][58];
> finalKey ^= ZobristTable[1][59];
> 
> finalKey ^= ZobristTable[2][84];
> finalKey ^= ZobristTable[2][90];
> 
> finalKey ^= ZobristTable[6][99];
> finalKey ^= ZobristTable[6][101];
> finalKey ^= ZobristTable[6][103];
> finalKey ^= ZobristTable[6][105];
> finalKey ^= ZobristTable[6][107];
> 
> // Red
> 
> finalKey ^= ZobristTable[13][147];
> finalKey ^= ZobristTable[13][149];
> finalKey ^= ZobristTable[13][151];
> finalKey ^= ZobristTable[13][153];
> finalKey ^= ZobristTable[13][155];
> 
> finalKey ^= ZobristTable[9][164];
> finalKey ^= ZobristTable[9][170];
> 
> finalKey ^= ZobristTable[8][195];
> finalKey ^= ZobristTable[10][196];
> finalKey ^= ZobristTable[11][197];
> finalKey ^= ZobristTable[12][198];
> finalKey ^= ZobristTable[7][199];
> finalKey ^= ZobristTable[12][200];
> finalKey ^= ZobristTable[11][201];
> finalKey ^= ZobristTable[10][202];
> finalKey ^= ZobristTable[8][203];
> 
> // turn of Red side
> finalKey ^= ZobristPlayer;

My result is "9114611293503372099". But I checked in my .obk file, the hashing key is "7101337512282506414".
I do not know how to run this algorithm exactly. Please help me explain it.

Thank you so much for reading.

**Comment by ianfab** [comment]
This project does not support obk, so this is the wrong place to ask.

**Comment by biennguyen13** [comment]
> This project does not support obk, so this is the wrong place to ask.

Thanks for replying.
okay, sorry I asked in the wrong place. Can you tell me where I can ask the question? Please!
