### ISSUE TITLE
template 'xiangqi' does not exist

### ISSUE THREAD

**Issue by skarl-api** [fairy-stockfish/Fairy-Stockfish#738]
./Fairy-Stockfish load variants.ini

Variant template 'xiangqi' does not exist.
Variant template 'janggi' does not exist.
Variant template 'janus' does not exist.
Variant template 'grand' does not exist.
Variant template 'capablanca' does not exist.
Variant template 'xiangqi' does not exist.
Variant template 'amazons' does not exist.
Variant template 'shogi' does not exist.

**Comment by skarl-api** [comment]
Fairy-Stockfish 14.0.1 by Fabian Fichter
Variant template 'xiangqi' does not exist.
Variant template 'janggi' does not exist.
Variant template 'janus' does not exist.
Variant template 'flipello' does not exist.
Variant template 'grand' does not exist.
Variant template 'capablanca' does not exist.
Variant template 'xiangqi' does not exist.
Variant template 'amazons' does not exist.
Variant template 'flipello' does not exist.
Variant template 'shogi' does not exist.

**Comment by ianfab** [comment]
Please ask such questions on discord or in the GitHub discussions, issues are for bug reports and feature requests.

You likely downloaded an 8x8 version instead of largeboards.
