### ISSUE TITLE
promotion region depending on piece type

### ISSUE THREAD

**Issue by t3kku** [fairy-stockfish/Fairy-Stockfish#744]
Hello,
I think this maybe similar to issue #618, but there should be a way to define the promotion region depending on the piece type.
As an example:
In shogi, the shogi-pawns and the other pieces can be promoted in the last three rows.
I think it would be nice if there were a way that the shogi-pawns could only be promoted in the last two rows while the other pieces could be promoted in the last three rows.
Thank you.

**Comment by ianfab** [comment]
Yes, that's one of the things the other issue is referring to. To keep discussion in one place I will close this one.
