### ISSUE TITLE
Support CheckShogi

### ISSUE THREAD

**Issue by M-DinhHoangViet** [fairy-stockfish/Fairy-Stockfish#747]
Just like standard shogi, but first to check opponent's king wins

**Comment by RainRat** [comment]
It sounds like it could be done with variants.ini with checkCounting and the number of checks set to 1.

**Comment by M-DinhHoangViet** [comment]
@RainRat yes
I think so, too

**Comment by ianfab** [comment]
Exactly, it is already supported

**Comment by M-DinhHoangViet** [comment]
https://fairy-stockfish.github.io/variants/
