### ISSUE TITLE
Adjudicate attax games when board is full

### ISSUE THREAD

**Issue by gbtami** [fairy-stockfish/Fairy-Stockfish#749]
Just to not forget it, I filed this issue.
From pychess Discord:

gbtami
 — 
12/18/2023 7:55 PM
Btw when the board is full it expects to make a "pass" move from both size to end the game by FSF adjudication
Maybe we can avoid it checking this on server side

ubdip
 — 
12/18/2023 8:27 PM
Not sure if the same might also happen in othello. If this is more generally applicable to many non-capture drop variants it should perhaps be implemented in Fairy-SF.

**Comment by ianfab** [comment]
Examples to reproduce:
```
setoption name UCI_variant value flipello
position fen pppppppp/pppppppp/pppPpppp/pPpPpppp/pppppppp/pPpPPPPP/ppPpPPpp/pppppppp[PPpp] b - - 63 32
go depth 5
```
```
setoption name UCI_variant value ataxx
position fen PPPpppp/pppPPPp/pPPPPPP/PPPPPPp/ppPPPpp/pPPPPpP/pPPPPPP b - - 99 50
go depth 5
```
