### ISSUE TITLE
Support Cylinder Chess

### ISSUE THREAD

**Issue by eskopp** [fairy-stockfish/Fairy-Stockfish#753]
![529906 bc3404f2 668x375o b73f4f323ab0@2x](https://github.com/fairy-stockfish/Fairy-Stockfish/assets/129506395/b679b1c7-3eb6-445a-833a-c6de1b32fda5)

Please Support Cylinder Chess.

Links:
 - [https://www.chess.com/blog/LogoCzar/cylindrical-chess](https://www.chess.com/blog/LogoCzar/cylindrical-chess)
 - [https://en.wikipedia.org/wiki/Cylinder_chess](https://en.wikipedia.org/wiki/Cylinder_chess)

Play:
- [https://www.cylinderchess.com/](https://www.cylinderchess.com/)

**Comment by osmiumic** [comment]
if this is to be added, i suggest that joining the top and bottom of the board should be possible too

**Comment by eskopp** [comment]
> if this is to be added, i suggest that joining the top and bottom of the board should be possible too

The idea of ​​connecting the top and bottom edges of the cylindrical chessboard is problematic as it constitutes a clear violation of the basic rules of chess. In particular, the placement of the kings next to each other in the initial setup is not allowed according to traditional chess rules.

**Comment by RainRat** [comment]
The initial layout of the pieces would be adjusted to match the toroidal board. https://www.zillions-of-games.com/cgi-bin/zilligames/submissions.cgi?do=show;id=3111

**Comment by nmccamish** [comment]
I would be content with just one side of the board being "glued," as opposed to some sort of toroidal or Klein board.

**Comment by eskopp** [comment]
I will close the issue. Apparently it has no relevance.

**Comment by eskopp** [comment]
I will close the issue. Apparently it has no relevance.

**Comment by ianfab** [comment]
It isn't irrelevant, but it requires big changes to move generation, so it won't happen any time soon.
