### ISSUE TITLE
-fexperimental-new-pass-manager is no longer valid for clang 16

### ISSUE THREAD

**Issue by xiota** [fairy-stockfish/Fairy-Stockfish#756]
`-fexperimental-new-pass-manager` was ignored in clang 15 and [removed in clang 16](https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html).
 
https://github.com/fairy-stockfish/Fairy-Stockfish/blob/6c8fb4630cc3a3771b6f7e7fa723464c1795a037/src/Makefile#L541-L543

Upstream stockfish solution is to check clang version in [Makefile#L619-L624](https://github.com/official-stockfish/Stockfish/blob/ededadcd6f7fbb9eb122f5fe336025cc4b11753b/src/Makefile#L619-L624):
```
	ifeq ($(comp),clang)
		clangmajorversion := $(shell $(CXX) -dumpversion 2>/dev/null | cut -f1 -d.)
		ifeq ($(shell expr $(clangmajorversion) \< 16),1)
			CXXFLAGS += -fexperimental-new-pass-manager
		endif
	endif
```

**Comment by ianfab** [comment]
Thanks. I cherry-picked the commit https://github.com/fairy-stockfish/Fairy-Stockfish/commit/052dce6a150c5dfc4a4775fc23319028904a86ab from upstream, should hopefully do the trick.
