### ISSUE TITLE
Migrating musketeer-stockfish to release 14

### ISSUE THREAD

**Issue by chris-heldeis** [fairy-stockfish/Fairy-Stockfish#776]
Hi Fabian,

Hope you are doing well.
I tried to migrate your musketeer-stockfish repository to release 14 of this repository since it is only working version for musketeer variant.
I've done it after fork this repository and here is the repository/branch link:
https://github.com/chris-heldeis/Fairy-Stockfish/tree/musketeer
It is built successfully but after import on winboard, it fails to load variant list.
I want to get some error logs but cannot do that by setting "Debug Log File" option in UCI::init
If you provide some guides or let me know what is problem in my migration, it would be so helpful for me.
I am looking forward to hear from you soon.

Best regards,
Christoph

**Comment by ianfab** [comment]
Hi, I am not sure these two repositories can be merged in a meaningful way. The two projects have a very different design and focus, so apart from both being based on SF they don't really share too much code. Therefore, if you are interested in updating the Musketeer-Stockfish code base, I would recommend to rather try to merge official SF into Musketeer-Stockfish, which also is not trivial, but should in principle work.
