### ISSUE TITLE
castling rules ignored in capablanca960

### ISSUE THREAD

**Issue by Curious2021** [fairy-stockfish/Fairy-Stockfish#790]
Castling rules are not respected in Capablanca960. i tried to castle my king in a valid position in a capablanca960 position and it wasn’t allowed. Why not? Okay so there was a bishop in the corner…but there was nothing between the king and the rook therefore it should have been allowed. So why wasn’t this allowed? After that game I checked the rules for Capablanca960 and it explicitly says it would follow the general rules for castling. Okay, i know the castling rules so this position clearly should have been allowed.

**Comment by Curious2021** [comment]
here’s the link to the game where i wasn’t allowed to castle. https://www.pychess.org/hFFmFD6h

**Comment by ianfab** [comment]
On the analysis board of the linked game I can castle anywhere from move 3 to 7, so I assume it is a non-issue, at least for Fairy-SF. Please report such issues first on the project where the issue occurs and only if you are sure that it is a Fairy-SF issue or a dev confirms report it here.
