### ISSUE TITLE
Representing a chess pawn in Betza notation

### ISSUE THREAD

**Issue by jaabsh1a** [fairy-stockfish/Fairy-Stockfish#796]
variants.ini says:

# See the list below for all available predefined piece types (and their Betza notation):
# pawn (fmWfceF)

How can I represent a standard pawn in a standard chess?
It can be useful for later modifications

In my opinion "n(ceF)[:=][QRNB]" is more accurate.
However it is not cover en passant capture.
Any suggestions on this issue?
Should variants.ini file be updated?

**Comment by ianfab** [comment]
I do not see the need for a change, the current description is fine. Promotion options are not part are not part of Betza notation.

**Comment by jaabsh1a** [comment]
> I do not see the need for a change, the current description is fine. Promotion options are not part are not part of Betza notation.

n( optionally {ef} | ceF )[:=][QRNB] or 
n(epd | ceF)[:=][QRNB] -epd stands for "en passant du" - from the starting rank
 are better options for standard chess pawn, but I am not sure.
 I am trying to build a new chess variant using a standard chess pawn as a prototype.
Are these 2 options good for this?
