### ISSUE TITLE
Remove doublepass=draw rule for "Wall or Move" variants

### ISSUE THREAD

**Issue by Belzedar94** [fairy-stockfish/Fairy-Stockfish#801]
Games are adjudicated as a draw when 2 walls are placed in a row in variants with "Wall or Move" rule.

For instance, in the variant "Atlantis":

FEN: `r1bq1rk1/pppn1pbp/3p1np*/*7/2PP4/P1N2N2/1PQ1BPPP/R1B1K*1R w KQ - 2 10`
Moves: `a1a1,a1e8 d6d6,d6b1`

The 2 passing moves adjudicate the game as a draw

**Comment by ianfab** [comment]
Should be fixed by #814.
