### ISSUE TITLE
Invalid move in Duck chess game

### ISSUE THREAD

**Issue by gbtami** [fairy-stockfish/Fairy-Stockfish#832]
Case described in https://github.com/gbtami/pychess-variants/issues/1678

If I add this to test.py test_get_fen() unittest
``` 
        fen = "r1b1k3/pp3pb1/4p3/2p2p2/2PpP2q/1P1P1P2/P1K1*3/RN1Q2N1 b q e3 0 17"
        moves = ["d4e3,e3d4"]
        result = sf.get_fen("duck", fen, moves)
        self.assertEqual(result, "r1b1k3/pp3pb1/4p3/2p2p2/2P*P2q/1P1PpP2/P1K5/RN1Q2N1 w q e3 1 18")
```
the result is
``` 
======================================================================
ERROR: test_get_fen (__main__.TestPyffish.test_get_fen)
----------------------------------------------------------------------
ValueError: Invalid move 'd4e3,e3d4'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tamas/Fairy-Stockfish/test.py", line 636, in test_get_fen
    result = sf.get_fen("duck", fen, moves)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in function get_fen> returned a result with an exception set

----------------------------------------------------------------------
Ran 20 tests in 1.288s

FAILED (errors=1)
```

**Comment by yjf2002ghty** [comment]
The same thing happens in fairyground.
![image](https://github.com/user-attachments/assets/bd4718d7-9b4d-4886-a8b0-4fc43f0c936c)
When setting the FEN to `r1b1k3/pp3pb1/4p3/2p2p2/2PpP2q/1P1P1P2/P1K1*3/RN1Q2N1 b q e3 0 17`, the actual FEN is `r1b1k3/pp3pb1/4p3/2p2p2/2PpP2q/1P1P1P2/P1K1*3/RN1Q2N1 b q - 0 17`. The en passant square isn't set correctly.

**Comment by gbtami** [comment]
Seems [c) there is no piece on epSquare or behind epSquare](https://github.com/fairy-stockfish/Fairy-Stockfish/blob/master/src/position.cpp#L441) is the root of this problem.

**Comment by ianfab** [comment]
Ah, so I guess it only happens when directly using the FEN and not when setting up via moves?

**Comment by gbtami** [comment]
I'm not sure about the latter, because the original issue raised in a human-engine game https://www.pychess.org/T2rNjEwo?ply=33
and we send initial FEN and move list to the fishnet workers here https://github.com/gbtami/pychess-variants/blob/master/server/ai.py#L46

**Comment by yjf2002ghty** [comment]
> Ah, so I guess it only happens when directly using the FEN and not when setting up via moves?

Yes, setting up via moves does not have this problem. So the problem is very likely caused by [c) there is no piece on epSquare or behind epSquare](https://github.com/fairy-stockfish/Fairy-Stockfish/blob/master/src/position.cpp#L441).

![image](https://github.com/user-attachments/assets/40816d4e-6aa9-4119-81a3-2dde8e6ed154)
