### ISSUE TITLE
Expansion of Where diagonalLines Applies

### ISSUE THREAD

**Issue by PraseodymiumSpike** [fairy-stockfish/Fairy-Stockfish#838]
Currently, the option `diagonalLines` in a variant configuration file doesn't work even for simple non-janggi cases like for a `chancellor` predefined piece or a piece defined with `customPiece1 = r:R`. It should work for all orthogonally-moving pieces by replacing `W` and `R` atoms with `K` and `Q` atoms with the extra movement restricted to the squares specified in the `diagonalLines` option.

**Comment by PraseodymiumSpike** [comment]
I have realized that what I proposed isn't a particularly good way to generalize what `diagonalLines` would do given that the janggi soldier, which I assume is defined as `fsW`, does not become either `fsK` or `fKsK` after `diagonalLines` is applied but instead becomes `fKsW`. So probably, only the vertical directions should be generalized: the orthogonally forwards direction would have the 2 diagonally forward directions added, and the orthogonally backwards direction would have the 2 diagonally backwards directions added.

**Comment by ianfab** [comment]
As indicated in the description this option is very specific for the Janggi pieces, and that is because it is a rather ugly implementation, since location dependent capture moves are very problematic e.g. for check detection. Therefore this option will remain as is.
